name: CI

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
        
            - name: Setup Go
              uses: actions/setup-go@v5
              with: 
                go-version: '>=1.23.0'
                cache: true
                cache-dependency-path: go.sum

            - name: OS Version
              run: cat /etc/os-release

            - name: Go Version
              run: go version

            - name: Go Lint
              uses: golangci/golangci-lint-action@v6

            - name: Go Build
              run: go build -v ./...

            - name: Generate test coverage
              run: go test ./... -coverprofile=./coverage.out -covermode=atomic -coverpkg=./...

            - name: Check test coverage
              uses: vladopajic/go-test-coverage@v2
              with:
                config: ./.testcoverage.yml
                profile: coverage.out
                local-prefix: github.com/org/project
                threshold-file: 80
                threshold-package: 80
                threshold-total: 95
                git-token: ${{ github.ref_name == 'main' }}
                git-branch: badges 
